### ISSUE TITLE
The server crashed when using dispenser

### ISSUE THREAD

**Issue by kliang04** [WerDei/Server-Hats#12] opened 2024-03-01 01:29 UTC
The server crashed when the dispenser was activated, no matter what items were inside.

I am using 1.20.4, and the mod version is Server Hats 1.20 - 0.16
I don't know if that is because I am using incompatible mods or the version is just wrong.
I removed the mod and the dispenser is good.
These are the other mods I am using:
MCDRcommandFabric-1.20.4-v1.2.1.jar
SecureExplosion-fabric-1.20.2-1.0.jar
entityculling-fabric-1.6.3.1-mc1.20.4.jar
essential_commands-0.35.0-mc1.20.4.jar
fabric-api-0.91.3+1.20.4.jar
fabric-carpet-1.20.3-1.4.128+v231205.jar
ferritecore-6.0.3-fabric.jar
lithium-fabric-mc1.20.4-0.12.1.jar
memoryleakfix-forge-1.17+-1.1.5.jar

**Comment by WerDei** [comment] 2024-03-01 16:01
Looks like a duplicate of #11

**Closed as not planned by WerDei** 2024-03-01 16:01 UTC
